# Generated by Django 4.1.3 on 2022-12-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_start', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('day_end', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('time_start', models.TimeField(blank=True, null=True, verbose_name='Время')),
                ('time_end', models.TimeField(blank=True, null=True, verbose_name='Время')),
                ('download', models.BooleanField(blank=True, null=True, verbose_name='Скачать')),
            ],
        ),
    ]
